# Generated by Django 3.0.5 on 2021-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelivErik', '0002_auto_20210325_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
