# Generated by Django 3.1.7 on 2021-03-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DelivErik', '0003_customer_customer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DelivErik.customer'),
        ),
    ]
